package Client_Java.WordyApp;


/**
* WordyApp/playersNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:05:19 PM SGT
*/

public final class playersNotFound extends org.omg.CORBA.UserException
{

  public playersNotFound ()
  {
    super(playersNotFoundHelper.id());
  } // ctor


  public playersNotFound (String $reason)
  {
    super(playersNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class playersNotFound
