package Client_Java.WordyApp;

/**
* WordyApp/usernameMismatchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:05:19 PM SGT
*/

public final class usernameMismatchHolder implements org.omg.CORBA.portable.Streamable
{
  public usernameMismatch value = null;

  public usernameMismatchHolder ()
  {
  }

  public usernameMismatchHolder (usernameMismatch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = usernameMismatchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    usernameMismatchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return usernameMismatchHelper.type ();
  }

}
