package Client_Java.WordyApp;


/**
* WordyApp/WordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:05:19 PM SGT
*/

public interface WordyOperations 
{
  String login (String name, String password) throws usernameMismatch, alreadyLoggedIn;
  void signOut (String username);
  boolean startGame (String username) throws playersNotFound;
  String[] requestLetters (String username);
  String sendWord (String username, String word) throws invalidWordLength, invalidWord;
  boolean checkTime (String username, int interval);
  String getRoundWinner (String username);
  String getGameWinner (String username);
  boolean checkReadyStatus (String username);
  String[][] getTopPlayers ();
  String[][] getTopWords ();
} // interface WordyOperations
