package Server_Java.WordyApp;

/**
* WordyApp/alreadyLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public final class alreadyLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public alreadyLoggedIn value = null;

  public alreadyLoggedInHolder ()
  {
  }

  public alreadyLoggedInHolder (alreadyLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = alreadyLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    alreadyLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return alreadyLoggedInHelper.type ();
  }

}
