package Server_Java.WordyApp;


/**
* WordyApp/alreadyLoggedIn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public final class alreadyLoggedIn extends org.omg.CORBA.UserException
{

  public alreadyLoggedIn ()
  {
    super(alreadyLoggedInHelper.id());
  } // ctor


  public alreadyLoggedIn (String $reason)
  {
    super(alreadyLoggedInHelper.id() + "  " + $reason);
  } // ctor

} // class alreadyLoggedIn
