package Server_Java.WordyApp;

/**
* WordyApp/invalidWordLengthHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public final class invalidWordLengthHolder implements org.omg.CORBA.portable.Streamable
{
  public invalidWordLength value = null;

  public invalidWordLengthHolder ()
  {
  }

  public invalidWordLengthHolder (invalidWordLength initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = invalidWordLengthHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    invalidWordLengthHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return invalidWordLengthHelper.type ();
  }

}
