package Server_Java.WordyApp;


/**
* WordyApp/playerWinsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public final class playerWinsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[][] = null;

  public playerWinsHolder ()
  {
  }

  public playerWinsHolder (String[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = playerWinsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    playerWinsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return playerWinsHelper.type ();
  }

}
