package Server_Java.WordyApp;

/**
* WordyApp/playersNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public final class playersNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public playersNotFound value = null;

  public playersNotFoundHolder ()
  {
  }

  public playersNotFoundHolder (playersNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = playersNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    playersNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return playersNotFoundHelper.type ();
  }

}
