package Server_Java.WordyApp;


/**
* WordyApp/Wordy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Wednesday, May 17, 2023 4:04:53 PM SGT
*/

public interface Wordy extends WordyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Wordy
