# Python stubs generated by omniidl from Wordy.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WordyApp"
#
__name__ = "WordyApp"
_0_WordyApp = omniORB.openModule("WordyApp", r"Wordy.idl")
_0_WordyApp__POA = omniORB.openModule("WordyApp__POA", r"Wordy.idl")


# typedef ... letters
class letters:
    _NP_RepositoryId = "IDL:WordyApp/letters:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyApp.letters = letters
_0_WordyApp._d_letters  = (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 17)
_0_WordyApp._ad_letters = (omniORB.tcInternal.tv_alias, letters._NP_RepositoryId, "letters", (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 17))
_0_WordyApp._tc_letters = omniORB.tcInternal.createTypeCode(_0_WordyApp._ad_letters)
omniORB.registerType(letters._NP_RepositoryId, _0_WordyApp._ad_letters, _0_WordyApp._tc_letters)
del letters

# typedef ... playerWins
class playerWins:
    _NP_RepositoryId = "IDL:WordyApp/playerWins:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyApp.playerWins = playerWins
_0_WordyApp._d_playerWins  = (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5)
_0_WordyApp._ad_playerWins = (omniORB.tcInternal.tv_alias, playerWins._NP_RepositoryId, "playerWins", (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5))
_0_WordyApp._tc_playerWins = omniORB.tcInternal.createTypeCode(_0_WordyApp._ad_playerWins)
omniORB.registerType(playerWins._NP_RepositoryId, _0_WordyApp._ad_playerWins, _0_WordyApp._tc_playerWins)
del playerWins

# typedef ... playerWords
class playerWords:
    _NP_RepositoryId = "IDL:WordyApp/playerWords:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyApp.playerWords = playerWords
_0_WordyApp._d_playerWords  = (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5)
_0_WordyApp._ad_playerWords = (omniORB.tcInternal.tv_alias, playerWords._NP_RepositoryId, "playerWords", (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5))
_0_WordyApp._tc_playerWords = omniORB.tcInternal.createTypeCode(_0_WordyApp._ad_playerWords)
omniORB.registerType(playerWords._NP_RepositoryId, _0_WordyApp._ad_playerWords, _0_WordyApp._tc_playerWords)
del playerWords

# exception alreadyLoggedIn
_0_WordyApp.alreadyLoggedIn = omniORB.newEmptyClass()
class alreadyLoggedIn (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/alreadyLoggedIn:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_WordyApp.alreadyLoggedIn = alreadyLoggedIn
_0_WordyApp._d_alreadyLoggedIn  = (omniORB.tcInternal.tv_except, alreadyLoggedIn, alreadyLoggedIn._NP_RepositoryId, "alreadyLoggedIn")
_0_WordyApp._tc_alreadyLoggedIn = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_alreadyLoggedIn)
omniORB.registerType(alreadyLoggedIn._NP_RepositoryId, _0_WordyApp._d_alreadyLoggedIn, _0_WordyApp._tc_alreadyLoggedIn)
del alreadyLoggedIn

# exception usernameMismatch
_0_WordyApp.usernameMismatch = omniORB.newEmptyClass()
class usernameMismatch (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/usernameMismatch:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_WordyApp.usernameMismatch = usernameMismatch
_0_WordyApp._d_usernameMismatch  = (omniORB.tcInternal.tv_except, usernameMismatch, usernameMismatch._NP_RepositoryId, "usernameMismatch")
_0_WordyApp._tc_usernameMismatch = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_usernameMismatch)
omniORB.registerType(usernameMismatch._NP_RepositoryId, _0_WordyApp._d_usernameMismatch, _0_WordyApp._tc_usernameMismatch)
del usernameMismatch

# exception playersNotFound
_0_WordyApp.playersNotFound = omniORB.newEmptyClass()
class playersNotFound (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/playersNotFound:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_WordyApp.playersNotFound = playersNotFound
_0_WordyApp._d_playersNotFound  = (omniORB.tcInternal.tv_except, playersNotFound, playersNotFound._NP_RepositoryId, "playersNotFound")
_0_WordyApp._tc_playersNotFound = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_playersNotFound)
omniORB.registerType(playersNotFound._NP_RepositoryId, _0_WordyApp._d_playersNotFound, _0_WordyApp._tc_playersNotFound)
del playersNotFound

# exception invalidWord
_0_WordyApp.invalidWord = omniORB.newEmptyClass()
class invalidWord (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/invalidWord:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_WordyApp.invalidWord = invalidWord
_0_WordyApp._d_invalidWord  = (omniORB.tcInternal.tv_except, invalidWord, invalidWord._NP_RepositoryId, "invalidWord")
_0_WordyApp._tc_invalidWord = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_invalidWord)
omniORB.registerType(invalidWord._NP_RepositoryId, _0_WordyApp._d_invalidWord, _0_WordyApp._tc_invalidWord)
del invalidWord

# exception invalidWordLength
_0_WordyApp.invalidWordLength = omniORB.newEmptyClass()
class invalidWordLength (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/invalidWordLength:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_WordyApp.invalidWordLength = invalidWordLength
_0_WordyApp._d_invalidWordLength  = (omniORB.tcInternal.tv_except, invalidWordLength, invalidWordLength._NP_RepositoryId, "invalidWordLength")
_0_WordyApp._tc_invalidWordLength = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_invalidWordLength)
omniORB.registerType(invalidWordLength._NP_RepositoryId, _0_WordyApp._d_invalidWordLength, _0_WordyApp._tc_invalidWordLength)
del invalidWordLength

# interface Wordy
_0_WordyApp._d_Wordy = (omniORB.tcInternal.tv_objref, "IDL:WordyApp/Wordy:1.0", "Wordy")
omniORB.typeMapping["IDL:WordyApp/Wordy:1.0"] = _0_WordyApp._d_Wordy
_0_WordyApp.Wordy = omniORB.newEmptyClass()
class Wordy :
    _NP_RepositoryId = _0_WordyApp._d_Wordy[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WordyApp.Wordy = Wordy
_0_WordyApp._tc_Wordy = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_Wordy)
omniORB.registerType(Wordy._NP_RepositoryId, _0_WordyApp._d_Wordy, _0_WordyApp._tc_Wordy)

# Wordy operations and attributes
Wordy._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_WordyApp.usernameMismatch._NP_RepositoryId: _0_WordyApp._d_usernameMismatch, _0_WordyApp.alreadyLoggedIn._NP_RepositoryId: _0_WordyApp._d_alreadyLoggedIn})
Wordy._d_signOut = (((omniORB.tcInternal.tv_string,0), ), (), None)
Wordy._d_startGame = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), {_0_WordyApp.playersNotFound._NP_RepositoryId: _0_WordyApp._d_playersNotFound})
Wordy._d_requestLetters = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:WordyApp/letters:1.0"], ), None)
Wordy._d_sendWord = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), ), {_0_WordyApp.invalidWordLength._NP_RepositoryId: _0_WordyApp._d_invalidWordLength, _0_WordyApp.invalidWord._NP_RepositoryId: _0_WordyApp._d_invalidWord})
Wordy._d_checkTime = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
Wordy._d_getRoundWinner = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
Wordy._d_getGameWinner = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
Wordy._d_checkReadyStatus = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
Wordy._d_getTopPlayers = ((), (omniORB.typeMapping["IDL:WordyApp/playerWins:1.0"], ), None)
Wordy._d_getTopWords = ((), (omniORB.typeMapping["IDL:WordyApp/playerWords:1.0"], ), None)

# Wordy object reference
class _objref_Wordy (CORBA.Object):
    _NP_RepositoryId = Wordy._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_WordyApp.Wordy._d_login, args)

    def signOut(self, *args):
        return self._obj.invoke("signOut", _0_WordyApp.Wordy._d_signOut, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_WordyApp.Wordy._d_startGame, args)

    def requestLetters(self, *args):
        return self._obj.invoke("requestLetters", _0_WordyApp.Wordy._d_requestLetters, args)

    def sendWord(self, *args):
        return self._obj.invoke("sendWord", _0_WordyApp.Wordy._d_sendWord, args)

    def checkTime(self, *args):
        return self._obj.invoke("checkTime", _0_WordyApp.Wordy._d_checkTime, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_WordyApp.Wordy._d_getRoundWinner, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_WordyApp.Wordy._d_getGameWinner, args)

    def checkReadyStatus(self, *args):
        return self._obj.invoke("checkReadyStatus", _0_WordyApp.Wordy._d_checkReadyStatus, args)

    def getTopPlayers(self, *args):
        return self._obj.invoke("getTopPlayers", _0_WordyApp.Wordy._d_getTopPlayers, args)

    def getTopWords(self, *args):
        return self._obj.invoke("getTopWords", _0_WordyApp.Wordy._d_getTopWords, args)

omniORB.registerObjref(Wordy._NP_RepositoryId, _objref_Wordy)
_0_WordyApp._objref_Wordy = _objref_Wordy
del Wordy, _objref_Wordy

# Wordy skeleton
__name__ = "WordyApp__POA"
class Wordy (PortableServer.Servant):
    _NP_RepositoryId = _0_WordyApp.Wordy._NP_RepositoryId


    _omni_op_d = {"login": _0_WordyApp.Wordy._d_login, "signOut": _0_WordyApp.Wordy._d_signOut, "startGame": _0_WordyApp.Wordy._d_startGame, "requestLetters": _0_WordyApp.Wordy._d_requestLetters, "sendWord": _0_WordyApp.Wordy._d_sendWord, "checkTime": _0_WordyApp.Wordy._d_checkTime, "getRoundWinner": _0_WordyApp.Wordy._d_getRoundWinner, "getGameWinner": _0_WordyApp.Wordy._d_getGameWinner, "checkReadyStatus": _0_WordyApp.Wordy._d_checkReadyStatus, "getTopPlayers": _0_WordyApp.Wordy._d_getTopPlayers, "getTopWords": _0_WordyApp.Wordy._d_getTopWords}

Wordy._omni_skeleton = Wordy
_0_WordyApp__POA.Wordy = Wordy
omniORB.registerSkeleton(Wordy._NP_RepositoryId, Wordy)
del Wordy
__name__ = "WordyApp"

#
# End of module "WordyApp"
#
__name__ = "Wordy_idl"

_exported_modules = ( "WordyApp", )

# The end.
